INSERT INTO works (user_uid, title, description, remote, price, per, city_id, standby, created_at, updated_at) VALUES
('usr-001', 'Reparo de Infiltrações', 'Identificação e conserto rápido de vazamentos em canos de PVC e cobre.', false, 150.00, 'Visita', 25, false, NOW(), NOW()),
('usr-002', 'Troca de Fiação', 'Substituição completa da fiação elétrica antiga com segurança.', false, 300.00, 'Projeto', 19, false, NOW(), NOW()),
('usr-003', 'Criação de Landing Page', 'Desenvolvimento de página de vendas otimizada e responsiva.', true, 1200.00, 'Projeto', 7, false, NOW(), NOW()),
('usr-004', 'Identidade Visual Completa', 'Criação de logo, paleta de cores e tipografia para sua marca.', true, 800.00, 'Projeto', 13, false, NOW(), NOW()),
('usr-005', 'Ensaio Externo', 'Sessão de fotos de 2 horas em parque ou praia, com 30 fotos editadas.', false, 450.00, 'Sessão', 1, false, NOW(), NOW()),
('usr-006', 'Terapia Online', 'Sessões de psicoterapia comportamental com 50 minutos de duração.', true, 120.00, 'Sessão', 25, false, NOW(), NOW()),
('usr-007', 'Inglês para Negócios', 'Aulas focadas em vocabulário corporativo e preparação para entrevistas.', true, 80.00, 'Hora', 21, false, NOW(), NOW()),
('usr-008', 'Consultoria Fitness', 'Montagem de treino mensal com acompanhamento via WhatsApp.', true, 150.00, 'Mês', 5, false, NOW(), NOW()),
('usr-009', 'Guarda-Roupa Sob Medida', 'Fabricação e montagem de guarda-roupa em MDF planejado.', false, 3500.00, 'Projeto', 16, false, NOW(), NOW()),
('usr-010', 'Reforma de Banheiro', 'Demolição, troca de revestimentos e instalação de louças novas.', false, 2800.00, 'Projeto', 8, false, NOW(), NOW()),
('usr-011', 'Maquiagem para Eventos', 'Make social completa com aplicação de cílios postiços.', false, 180.00, 'Sessão', 24, false, NOW(), NOW()),
('usr-012', 'Corte e Mechas', 'Transformação completa com técnicas de balayage ou luzes.', false, 350.00, 'Serviço', 14, false, NOW(), NOW()),
('usr-013', 'Análise de Contratos', 'Revisão detalhada de contratos de aluguel ou prestação de serviços.', true, 250.00, 'Contrato', 7, false, NOW(), NOW()),
('usr-014', 'Imposto de Renda PF', 'Organização e envio da sua declaração anual do imposto de renda.', true, 150.00, 'Serviço', 9, false, NOW(), NOW()),
('usr-015', 'Projeto de Interiores 3D', 'Planta baixa e imagens em 3D para reforma da sua sala de estar.', true, 1500.00, 'Ambiente', 12, false, NOW(), NOW()),
('usr-016', 'Tradução de Artigos', 'Tradução de textos acadêmicos do inglês para o português.', true, 0.15, 'Palavra', 2, false, NOW(), NOW()),
('usr-017', 'Artigo Otimizado (SEO)', 'Texto de até 1000 palavras otimizado para o Google.', true, 100.00, 'Artigo', 10, false, NOW(), NOW()),
('usr-018', 'Plano Alimentar Mensal', 'Consulta online com entrega de dieta personalizada em app.', true, 200.00, 'Consulta', 18, false, NOW(), NOW()),
('usr-019', 'Faxina Pesada', 'Limpeza detalhada de todos os cômodos, janelas e área externa.', false, 220.00, 'Diária', 17, false, NOW(), NOW()),
('usr-020', 'Passeio Recreativo de 1h', 'Caminhada focada em gastar a energia do seu cachorro de forma segura.', false, 40.00, 'Passeio', 23, false, NOW(), NOW());